language: node_js
node_js:
  - 10
cache:
  - npm
install:
  - npm install
script:
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git init
    git config user.name "ArranGravestock"
    git config user.email "arran@gravestock.net"
    git remote add upstream "https://$GITHUB_API_KEYN@github.com/<me>/shane-gravestock.git"
    git fetch upstream
    git reset upstream/gh-pages
    cd "$TRAVIS_BUILD_DIR"
    git add -A .
    git commit -m "rebuild pages"
    git push -q upstream HEAD:gh-pages
  fi
