language: node_js
node_js:
  - 10
cache:
  - npm
install:
  - npm install
script:
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git init
    git checkout -b production
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    git push -f -q https://<me>:$GITHUB_API_KEY@github.com/<me>/<myrepo>-production production &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
